models:
  - name: "LLaMA 8B"
    base_url: "http://10.10.10.200:8000/v1"
    model_id: "meta/llama3-8b-instruct"
    api_key: "not-needed"
  
  - name: "LLaMA 70B"
    base_url: "http://10.10.10.200:8001/v1"
    model_id: "meta/llama3-70b-instruct"
    api_key: "not-needed" 